// <auto-generated />
using BibliotecaWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BibliotecaWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260918035746_ValidacionLibros")]
    partial class ValidacionLibros
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BibliotecaWeb.Models.Libro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnioPublicacion")
                        .HasColumnType("int");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Disponibles")
                        .HasColumnType("int");

                    b.Property<string>("ImagenNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Libros");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnioPublicacion = 1967,
                            Autor = "Gabriel García Márquez",
                            Categoria = "Novela",
                            Descripcion = "La saga de la familia Buendía en el pueblo de Macondo, obra cumbre del realismo mágico.",
                            Disponibles = 3,
                            ImagenNombre = "cien-anios-de-soledad.svg",
                            Titulo = "Cien años de soledad"
                        },
                        new
                        {
                            Id = 2,
                            AnioPublicacion = 1982,
                            Autor = "Isabel Allende",
                            Categoria = "Novela",
                            Descripcion = "Tres generaciones de la familia Trueba en un país latinoamericano marcado por el cambio.",
                            Disponibles = 2,
                            ImagenNombre = "la-casa-de-los-espiritus.svg",
                            Titulo = "La casa de los espíritus"
                        },
                        new
                        {
                            Id = 3,
                            AnioPublicacion = 1963,
                            Autor = "Mario Vargas Llosa",
                            Categoria = "Novela",
                            Descripcion = "La vida de un grupo de cadetes en un colegio militar de Lima.",
                            Disponibles = 0,
                            ImagenNombre = "la-ciudad-y-los-perros.svg",
                            Titulo = "La ciudad y los perros"
                        },
                        new
                        {
                            Id = 4,
                            AnioPublicacion = 1605,
                            Autor = "Miguel de Cervantes",
                            Categoria = "Clásico",
                            Descripcion = "Las aventuras del ingenioso hidalgo y su escudero Sancho Panza.",
                            Disponibles = 1,
                            ImagenNombre = "don-quijote-de-la-mancha.svg",
                            Titulo = "Don Quijote de la Mancha"
                        },
                        new
                        {
                            Id = 5,
                            AnioPublicacion = 1966,
                            Autor = "Claribel Alegría",
                            Categoria = "Novela",
                            Descripcion = "Una historia de amor enmarcada en la matanza salvadoreña de 1932.",
                            Disponibles = 0,
                            ImagenNombre = "cenizas-de-izalco.svg",
                            Titulo = "Cenizas de Izalco"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
